version: '2'
services:
  app:
    build: 
      context: ./docker
      dockerfile: Dockerfile-app
    environment:
      APP_ENV: dev
    command: bash -c "/usr/sbin/apache2ctl -D FOREGROUND"
    volumes:
      - ./magento:/home/www/magento
    ports:
      - 80:80
    tty: true
#    depends_on:
#      - mysql
#      - memcache
#    cpu_shares: 512
#  mysql:
#    build:
#      context: ./docker
#      dockerfile: Dockerfile-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: droot
#      MYSQL_DATABASE: ec24h_e-krzeslo
#      MYSQL_USER: ec24h
#      MYSQL_PASSWORD: 3c24hhh
#    volumes:
#      - ../e-krzeslo-data/mysql:/var/lib/mysql
#      - ./docker/mysql/conf.d:/etc/mysql/conf.d
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --init-connect='SET NAMES UTF8;' --max_allowed_packet=64M
#  memcache:
#    image: memcached:1.4-alpine
#    mem_limit: 16777216
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - 9090:80
#    environment:
#      PMA_HOST: mysql
