FROM ubuntu:16.04

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
        software-properties-common \
    && export LANG=C.UTF-8 \
    && add-apt-repository -y ppa:ondrej/php \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
		apache2 \
        nano \
        vim \
        cron \
		mysql-client \
        mc \
    && apt-get install -y --allow-unauthenticated \
        php7.0 \ 
        libapache2-mod-php7.0 \
        php7.0 php7.0-common \
        php7.0-gd \
        php7.0-mysql \
        php7.0-mcrypt \
        php7.0-curl \
        php7.0-intl \
        php7.0-xsl \
        php7.0-mbstring \
        php7.0-zip \
        php7.0-bcmath \
        php7.0-iconv \		
	&& rm -r /var/lib/apt/lists/* \
	&& apt-get clean

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

COPY default.conf /etc/apache2/sites-available/000-default.conf
COPY servername.conf /etc/apache2/conf-available/servername.conf
COPY php.ini /etc/php/7.0/apache2/php.ini

WORKDIR /home/www/magento

RUN a2enconf servername && a2enmod rewrite && a2enmod expires 

EXPOSE 80
