FROM ubuntu:16.04

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:ondrej/php \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
		apache2 \
    && apt-get install -y --allow-unauthenticated php7.0 libapache2-mod-php7.0 php7.0 php7.0-common php7.0-gd php7.0-mysql php7.0-mcrypt php7.0-curl php7.0-intl php7.0-xsl php7.0-mbstring php7.0-zip php7.0-bcmath php7.0-iconv \		
	&& rm -r /var/lib/apt/lists/* \
	&& apt-get clean

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

#COPY default.conf /etc/apache2/sites-available/default
#COPY 20-xdebug.ini /etc/php5/conf.d/20-xdebug.ini

RUN a2enmod rewrite && a2enmod expires 
#&& touch /var/log/cron.log && cron

WORKDIR /home/www/magento

EXPOSE 95

#VOLUME /var/log/ ../.log

#CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
